#!/usr/bin/env python3
"""
Notion Database Setup Script
Creates all required databases for the marketing agency system
"""

import os
import json
import sys
from notion_helper import NotionHelper

def setup_notion_databases():
    """Create all required Notion databases"""
    
    # Load database schema
    with open("notion_database_schema.json", "r") as f:
        schema = json.load(f)
    
    # Initialize Notion helper
    try:
        helper = NotionHelper()
        print("✅ Notion API connection successful")
    except ValueError as e:
        print(f"❌ Notion setup failed: {e}")
        print("Please set your NOTION_API_KEY environment variable")
        return False
    
    # Create each database
    database_ids = {}
    
    for db_name, db_schema in schema["databases"].items():
        try:
            print(f"Creating database: {db_schema['name']}...")
            db_id = helper.create_database(db_name, db_schema)
            database_ids[db_name] = db_id
            print(f"✅ Created {db_schema['name']} (ID: {db_id})")
        except Exception as e:
            print(f"❌ Failed to create {db_schema['name']}: {e}")
            return False
    
    # Save database IDs to environment file
    env_content = f"""# Notion Integration Environment Variables
# Generated by setup_notion.py

# Notion API Configuration
NOTION_API_KEY={os.getenv('NOTION_API_KEY', 'your_notion_api_key_here')}
NOTION_PAGE_ID={os.getenv('NOTION_PAGE_ID', 'your_notion_page_id_here')}

# Database IDs (auto-generated)
NOTION_CLIENTS_DB_ID={database_ids.get('clients', '')}
NOTION_REPORTS_DB_ID={database_ids.get('reports', '')}
NOTION_ACTION_ITEMS_DB_ID={database_ids.get('action_items', '')}
NOTION_RESEARCH_DB_ID={database_ids.get('research_insights', '')}
NOTION_CONTENT_DB_ID={database_ids.get('content_assets', '')}
NOTION_METRICS_DB_ID={database_ids.get('performance_metrics', '')}

# Optional: Enable/disable Notion sync
ENABLE_NOTION_SYNC=true
"""
    
    with open("config.env", "w") as f:
        f.write(env_content)
    
    print("\n🎉 All databases created successfully!")
    print("📝 Database IDs saved to config.env file")
    print("\nNext steps:")
    print("1. Copy config.env to your main project directory as .env")
    print("2. Update NOTION_PAGE_ID with your actual Notion page ID")
    print("3. Test the integration with: python test_notion_sync.py")
    
    return True

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--help":
        print("Notion Database Setup")
        print("====================")
        print("This script creates all required Notion databases for the marketing agency system.")
        print("\nPrerequisites:")
        print("1. Set NOTION_API_KEY environment variable")
        print("2. Set NOTION_PAGE_ID environment variable (ID of the page where databases will be created)")
        print("\nUsage:")
        print("python setup_notion.py")
        print("\nAfter running, database IDs will be saved to .env file")
    else:
        setup_notion_databases()
